"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import TopBar from "@/components/TopBar";
import React from "react";
import { SunIcon } from "@radix-ui/react-icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  context: any;
}>) {
  const [showPanel, setShowPanel] = React.useState(false);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <button
          onClick={() => setShowPanel(!showPanel)}
          className={
            showPanel
              ? "absolute rounded-full w-8 h-8 flex items-center justify-center z-10 bottom-4 right-4 border-2 border-blue-500"
              : "absolute rounded-full w-8 h-8 flex items-center justify-center z-10 bottom-4 right-4 border-2 border-black"
          }
        >
          <SunIcon color={showPanel ? "blue" : "black"} />
        </button>
        <Theme accentColor="orange" grayColor="olive">
          <TopBar />
          {children}
          {showPanel ? <ThemePanel /> : <></>}
        </Theme>
      </body>
    </html>
  );
}
